name: Run Test

on:
  pull_request:
    paths:
      - '**'

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get changed files
        id: get-changed-files
        run: |
          changed_files=$(git diff --name-only HEAD^ HEAD)
          echo "::set-output name=files::${changed_files}"

      - name: Run test_file.py on changed files
        run: |
          IFS=$'\n' read -d '' -ra files <<< "${{ steps.get-changed-files.outputs.files }}"
          for file in "${files[@]}"; do
            python test_file.py "$file"
          done
